# Generated by Django 3.2.7 on 2021-09-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(db_column='doctor_pk', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='management.doctor')),
                ('patient', models.ForeignKey(db_column='patient_pk', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='management.patient')),
            ],
        ),
    ]
